Lamoda\Metric\MetricBundle\Entity\Metric:
  type: mappedSuperclass
  id:
    id:
      type: guid
      generator:
        strategy: UUID
  uniqueConstraints:
    metric_key_tags_unique:
      columns:
      - name
      - tags
  fields:
    name: { type: string }
    value: { type: float }
    tags: { type: json_array }
