Lamoda\MetricBundle\Entity\MetricGroup:
  type: mappedSuperclass
  id:
    name: { type: string }
  fields:
    tags: { type: json_array }
  manyToMany:
    metrics:
      targetEntity: Lamoda\MetricResponder\MetricInterface
      joinTable:
        name: metric_group_metric
        joinColumns:
          group_name:
            referencedColumnName: name
        inverseJoinColumns:
          metric_key:
            referencedColumnName: key
