services:
  lamoda_metrics.metric_mutator:
    class: Lamoda\Metric\Storage\StoredMetricMutator
    arguments: []
    public: false

  Lamoda\Metric\Storage\MetricMutatorInterface:
    alias: lamoda_metrics.metric_mutator

  lamoda_metrics.route_loader:
    class: Lamoda\Metric\MetricBundle\Routing\MetricRouteLoader
    public: false
    tags:
    - { name: routing.loader }

  lamoda_metrics.storage_registry:
    class: Lamoda\Metric\Storage\StorageRegistry
    public: false

  lamoda_metrics.collector_registry:
    class: Lamoda\Metric\Collector\CollectorRegistry
    public: false

  lamoda_metrics.dump_command:
    class: Lamoda\Metric\MetricBundle\Command\DebugMetricsCommand
    arguments:
    - "@lamoda_metrics.collector_registry"
    public: true
    tags:
    - {name: console.command, command: 'metrics:debug'}

  lamoda_metrics.materialize_command:
    class: Lamoda\Metric\MetricBundle\Command\MaterializeMetricsCommand
    arguments:
    - "@lamoda_metrics.collector_registry"
    - "@lamoda_metrics.storage_registry"
    public: true
    tags:
    - {name: console.command, command: 'metrics:materialize'}
