services:
  lamoda_metrics.metric_storage:
    class: Lamoda\Metric\Storage\DelegatingMetricStorage
    public: false

  Lamoda\MetricStorage\AdjustableMetricStorageInterface:
    alias: lamoda_metrics.metric_storage

  lamoda_metrics.metric_adjuster:
    class: Lamoda\Metric\Storage\MetricAdjuster
    arguments:
    - '@Lamoda\MetricStorage\AdjustableMetricStorageInterface'
    public: false

  Lamoda\MetricStorage\MetricAdjusterInterface:
    alias: lamoda_metrics.metric_adjuster

  lamoda_metrics.route_loader:
    class: Lamoda\Metric\MetricBundle\Routing\MetricRouteLoader
    tags:
    - { name: routing.loader }

  lamoda_metrics.receiver_registry:
    class: Lamoda\Metric\Storage\ReceiverRegistry
    public: false

  lamoda_metrics.collector_registry:
    class: Lamoda\Metric\Collector\CollectorRegistry
    public: false

  lamoda_metrics.dump_command:
    class: Lamoda\Metric\MetricBundle\Command\DebugMetricsCommand
    arguments:
    - "@lamoda_metrics.collector_registry"
    public: false
    tags:
    - {name: console.command, command: 'metrics:debug'}

  lamoda_metrics.materialize_command:
    class: Lamoda\Metric\MetricBundle\Command\MaterializeMetricsCommand
    arguments:
    - "@lamoda_metrics.collector_registry"
    - "@lamoda_metrics.receiver_registry"
    public: false
    tags:
    - {name: console.command, command: 'metrics:materialize'}
